# Generated by Django 3.1.7 on 2021-10-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='event',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
