# Generated by Django 3.1.7 on 2021-10-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_invites_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('checkinType', models.CharField(max_length=64)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkins.invites')),
            ],
        ),
    ]
