# Generated by Django 3.1.7 on 2021-10-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0004_checkins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkins',
            name='data',
        ),
        migrations.AddField(
            model_name='checkins',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='checkins',
            name='event',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='checkins',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='checkins',
            name='checkinType',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='checkins',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
